name: yolo-detection-app
channels:
  - conda-forge
  - anaconda
  - nvidia
  - pytorch
  - pip
dependencies:
  - ultralytics
  - py-opencv
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 # Restart may be required
  - pyzbar
  - pip
